default:
  image: amazoncorreto:19.0.1-alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - main

test:
  stage: test
  script:
    - ./gradlew test