default:
  image: amazoncorretto:19.0.1-alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/
  only:
    - main

test:
  stage: test
  script:
    - ./gradlew test
  only:
    - main
    - merge_requests